config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  unauthenticated :user do
    root to: 'users#index'
  end

  authenticated :user do
    root to: 'categories#index', as: :authenticated_root
  end

  resources :categories do
    resources :transactions
  end

  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :transactions

  validates :user_id, presence: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :category_id, presence: true
  validates :amount, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :email, presence: true

  has_many :transactions
  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end

  def after_sign_up_path_for(_resource)
    root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @user = current_user
    @categories = current_user.categories
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.create(category_params)
    if @category.save
      flash[:notice] = 'Congratulations... Your Category was successfully created.'
    else
      flash.now[:notice] = 'Oups! Impossible to created to create a category'
    end
    redirect_to root_path
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = 'Oups! Category removed successfully'
    redirect_to root_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon, :user_id)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]

  def index
    @category = Category.find(params[:category_id])
    @transactions = @category.transactions.order(created_at: :desc)
    @total_money = @transactions.sum(:amount)
  end

  def show; end

  def new
    @user = current_user
    @category = Category.find(params[:category_id])
    @transaction = Transaction.new
  end

  def edit; end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user_id = current_user.id
    @transaction.category_id = Category.find_by_id(params[:category_id]).id
    respond_to do |format|
      if @transaction.save
        format.html do
          redirect_to category_transactions_path(@transaction.category_id),
                      notice: 'Congratulations, Your Transaction was successfully created.'
        end
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(:user_id, :name, :category_id, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def example_img(category)
    img_example = '/assets/budgetimage.png'
    category.icon.present? and category.icon.last(4) == '.png' ? category.icon : img_example
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/categories/_category.html.erb
<div class="single-cat" id="<%= dom_id category %>">
 <div class="category-img">
    <%= image_tag example_img(category), class: "cat-img" %>
  </div>
  <p class = "cat-details">
    <strong><%= category.name %></strong>
    <span>$ <%= category.transactions.all.sum(:amount) %> </span>
  </p>
</div>

app/views/categories/_form.html.erb
<div class="container">
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> You can not save this category:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, class: "form-label", style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :icon, class: "form-label", style: "display: block" %>
    <%= form.url_field :icon, class: "form-control", placeholder: "Add a valid png URL" %>
  </div><br>

  <div class="buttons-main">
    <%= form.submit class: "btn btn-success", id: "btn-log" %>
  </div>
<% end %>
</div>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show category", @category %> |
  <%= link_to "Back", categories_path %>
</div>

app/views/categories/index.html.erb
<div class="my-header">
<div class="back">
    <a class="link" href="/"><svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
    </svg></a>
</div>
  <h2>Categories</h2>
<p class= "out"><%= link_to "Sign out", destroy_user_session_path, class: "sign-out", method: :delete, data: { confirm: 'Are you sure?' } %></p>
</div>
<div class="page">
<div class="container">
<div class="section-main">
  <% @categories.each do |category| %>
  <a class="cat" href = "/categories/<%= category.id %>/transactions" >
    <%= render category %>
  <% end %>
</div>
  <div class = "add-category">
    <%= link_to "New category", new_category_path, class: "new" %>
  </div>
</div>
</div>

app/views/categories/new.html.erb
<div class="my-header">
<p style="color: green"><%= notice %></p>
<div class="back">
    <a class="link" href="/categories"><svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
    </svg></a>
</div>
  <h2>Categories</h2>
<p class= "out"><%= link_to "Sign out", destroy_user_session_path, class: "sign-out", method: :delete, data: { confirm: 'Are you sure?' } %></p>
</div>
<h2>Add a new category</h2>
<%= render "form", category: @category %>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Delete category", @category, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>MyBudgetApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
   <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
   <% end %>
    <%= yield %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/transactions/_form.html.erb
<div class="container">
<%= form_with model: [@category, @category.transactions.create]  do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> You can not save this transaction:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, class: "form-label", style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :amount, class: "form-label", style: "display: block" %>
    <%= form.number_field :amount, class: "form-control" %>
  </div><br>

  <div class="buttons-main">
    <%= form.submit class: "btn btn-success", id: "btn-log" %>
  </div>
<% end %>
</div>

app/views/transactions/_transaction.html.erb
<div class="single-cat" id="<%= dom_id transaction %>">

  <div class="category-img">
    <%= image_tag example_img(@category), class: "cat-img" %>
  </div>
  <p class="cat-details">
    <strong><%= transaction.name %></strong>
    <span> <%= transaction.amount %> $</span>
  </p>
</div>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show transaction", @transaction %> |
  <%= link_to "Back", transactions_path %>
</div>

app/views/transactions/index.html.erb
<div class="my-header">
<div class="back">
    <a class="link" href="/categories"><svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
    </svg></a>
</div>
  <h2>Transactions</h2>
<p class= "out"><%= link_to "Sign out", destroy_user_session_path, class: "sign-out", method: :delete, data: { confirm: 'Confirm if you want to quit?' } %></p>
</div>
<div class="page">
<div class="container">
  <div class="section-main">
    <p>Category Name:
      <%= @category.name%>
    </p>
    <p>Total amount: <%= @total_money %>$ </p>
      <% @transactions.each do |transaction| %>
        <%= render transaction %>
      <% end %>
  </div>
  <div class = "add-category">
    <%= link_to "New transaction", new_category_transaction_path(@category.id), class: "new" %>
  </div>
</div>
</div>

app/views/transactions/new.html.erb
<div class="my-header">
<p style="color: green"><%= notice %></p>
<div class="back">
    <a class="link" href="/categories/<%= @category.id %>/transactions"> <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
    </svg></a>
</div>
  <h2>Transactions</h2>
<p class= "out"><%= link_to "Sign out", destroy_user_session_path, class: "sign-out", method: :delete, data: { confirm: 'Are you sure?' } %></p>
</div>
<h2>New transaction</h2>
<%= render "form", transaction: @transaction %>

app/views/transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @transaction %>

<div>
  <%= link_to "Edit this transaction", edit_transaction_path(@transaction) %> |
  <%= link_to "Back to transactions", transactions_path %>

  <%= button_to "Delete transaction", @transaction, method: :delete %>
</div>

app/views/users/index.html.erb
<div class="container">
	  <div class="my-logo">
        <%= image_tag("budgetimage.png", width:'200px', class: "img", height:'160px') %>
      </div>
	<div class="buttons-main">
		<%= link_to 'Log in', new_user_session_url, id: "btn-log", class: "btn btn-success" %>
		<%= link_to 'Sign up', new_user_registration_url, id: "btn-sign", class: "btn btn-primary" %>
	</div>
</div>